# Generated by Django 3.2.3 on 2021-06-03 21:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('instrument', models.JSONField(blank=True, null=True)),
                ('ensemble', models.JSONField(blank=True, null=True)),
                ('format', models.CharField(max_length=50)),
                ('level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Cannot input cost amount lower than $0!')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('fpath', models.TextField(blank=True, null=True, verbose_name='file path')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sheetmusic')),
            ],
            options={
                'ordering': ['product', 'name'],
            },
        ),
    ]
