# Generated by Django 3.2.3 on 2021-06-03 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210603_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmusic',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Cannot input cost amount lower than $0!')]),
        ),
    ]
