# Generated by Django 3.2.3 on 2021-06-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_sheetmusic_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmusic',
            name='original',
            field=models.BooleanField(default=False),
        ),
    ]
