# Generated by Django 3.2.3 on 2021-06-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sheetmusic_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=75, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=75, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=75, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='sheetmusic',
            name='ensemble',
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='img_path',
            field=models.URLField(blank=True, null=True, verbose_name='image path'),
        ),
        migrations.RemoveField(
            model_name='sheetmusic',
            name='format',
        ),
        migrations.AlterField(
            model_name='sheetmusic',
            name='fpath',
            field=models.URLField(blank=True, null=True, verbose_name='file path'),
        ),
        migrations.RemoveField(
            model_name='sheetmusic',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='sheetmusic',
            name='instrument',
        ),
        migrations.AlterField(
            model_name='sheetmusic',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Early Intermediate'), (3, 'Intermediate'), (4, 'Advanced Intermediate'), (5, 'Advanced')], default=1),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='format',
            field=models.ManyToManyField(to='shop.Format'),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='genre',
            field=models.ManyToManyField(to='shop.Genre'),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='instrument',
            field=models.ManyToManyField(to='shop.Instrument'),
        ),
    ]
