# Generated by Django 3.2.3 on 2021-06-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210610_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmusic',
            name='composer',
            field=models.CharField(default='Juan Carlos Davila', max_length=50),
        ),
    ]
