# Generated by Django 3.2.3 on 2021-06-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_sheetmusic_composer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmusic',
            name='composer',
            field=models.CharField(max_length=50),
        ),
    ]
