# Generated by Django 3.2.3 on 2021-06-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
