# Generated by Django 3.2.3 on 2021-07-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
